name: tecnoanjos_franquia
description: Admin da franquia tecnoanjos

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flavor:
  string_validator:
  jwt_decode:
  flux_validator_dart: ^1.0.3
  mask_shifter: ^0.1.0
  horizontal_data_table: ^2.1.1+1
  flutter_html: ^1.1.1
  flutter_svg: ^0.19.2+1

  universal_html: ^1.2.3

  search_cep:
  localstorage: ^3.0.2+5
  qrscan: ^0.2.17
  sentry: ^3.0.1
  progress_dialog: ^1.2.4
  responsive_grid: ^1.2.1+1
  flutter_animated_dialog: ^1.1.0
  device_info: ^0.4.2+7
  flutter_masked_text: ^0.8.0
  flutter_secure_storage: ^3.3.3
  auto_size_text: ^2.1.0

  google_fonts: ^1.1.0
  flutter_icons: ^1.1.0
  draggable_scrollbar: ^0.0.4
  dio: ^3.0.10
  rxdart: ^0.24.1
  flutter_modular: 3.0.2+1
  crypto: ^2.1.5
  percent_indicator: ^2.1.5
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # Use with the CupertinoIcons class for iOS style icons.
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  mockito: ^4.1.4
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
